-- Создание таблицы в PostgreSQL
DROP TABLE IF EXISTS mock_data;

CREATE TABLE mock_data (
    id INTEGER,
    customer_first_name VARCHAR(50),
    customer_last_name VARCHAR(50),
    customer_age INTEGER,
    customer_email VARCHAR(100),
    customer_country VARCHAR(50),
    customer_postal_code VARCHAR(20),
    customer_pet_type VARCHAR(20),
    customer_pet_name VARCHAR(50),
    customer_pet_breed VARCHAR(50),
    seller_first_name VARCHAR(50),
    seller_last_name VARCHAR(50),
    seller_email VARCHAR(100),
    seller_country VARCHAR(50),
    seller_postal_code VARCHAR(20),
    product_name VARCHAR(100),
    product_category VARCHAR(50),
    product_price DECIMAL(10,2),
    product_quantity INTEGER,
    sale_date DATE,
    sale_customer_id INTEGER,
    sale_seller_id INTEGER,
    sale_product_id INTEGER,
    sale_quantity INTEGER,
    sale_total_price DECIMAL(10,2),
    store_name VARCHAR(100),
    store_location VARCHAR(100),
    store_city VARCHAR(50),
    store_state VARCHAR(20),
    store_country VARCHAR(50),
    store_phone VARCHAR(20),
    store_email VARCHAR(100),
    pet_category VARCHAR(30),
    product_weight DECIMAL(8,1),
    product_color VARCHAR(20),
    product_size VARCHAR(10),
    product_brand VARCHAR(50),
    product_material VARCHAR(30),
    product_description TEXT,
    product_rating DECIMAL(3,1),
    product_reviews INTEGER,
    product_release_date DATE,
    product_expiry_date DATE,
    supplier_name VARCHAR(100),
    supplier_contact VARCHAR(100),
    supplier_email VARCHAR(100),
    supplier_phone VARCHAR(20),
    supplier_address VARCHAR(200),
    supplier_city VARCHAR(50),
    supplier_country VARCHAR(50)
);

-- Проверка создания таблицы
SELECT 'PostgreSQL table mock_data created successfully' AS status;