-- Создание таблицы в ClickHouse
DROP TABLE IF EXISTS mock_data;

CREATE TABLE mock_data (
    id UInt32,
    customer_first_name String,
    customer_last_name String,
    customer_age UInt8,
    customer_email String,
    customer_country String,
    customer_postal_code String,
    customer_pet_type String,
    customer_pet_name String,
    customer_pet_breed String,
    seller_first_name String,
    seller_last_name String,
    seller_email String,
    seller_country String,
    seller_postal_code String,
    product_name String,
    product_category String,
    product_price Decimal(10,2),
    product_quantity UInt16,
    sale_date Date,
    sale_customer_id UInt32,
    sale_seller_id UInt32,
    sale_product_id UInt32,
    sale_quantity UInt16,
    sale_total_price Decimal(10,2),
    store_name String,
    store_location String,
    store_city String,
    store_state String,
    store_country String,
    store_phone String,
    store_email String,
    pet_category String,
    product_weight Decimal(8,1),
    product_color String,
    product_size String,
    product_brand String,
    product_material String,
    product_description String,
    product_rating Decimal(3,1),
    product_reviews UInt32,
    product_release_date Date,
    product_expiry_date Date,
    supplier_name String,
    supplier_contact String,
    supplier_email String,
    supplier_phone String,
    supplier_address String,
    supplier_city String,
    supplier_country String
) ENGINE = MergeTree()
ORDER BY (sale_date, id);

-- Проверка создания таблицы
SELECT 'ClickHouse table mock_data created successfully' AS status;